version: "3.7"
services:
  fastapi:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - LIBGL_PATH=/usr/lib/x86_64-linux-gnu/libGL.so.1
    runtime : nvidia
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - my_network
    

  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastapi
    networks:
      - my_network

  redis:
    image: redis
    networks:
      - my_network

networks:
  my_network:
